### ISSUE TITLE
Quickstart broken: AttributeError: 'VoilaExporter' object has no attribute 'contents_manager'

### ISSUE THREAD

**Issue by robmarkcole** [jtpio/voila-gpx-viewer#21]
Following the quickstart I get:
```
AttributeError: 'VoilaExporter' object has no attribute 'contents_manager'
```

**Comment by jtpio** [comment]
Thanks @robmarkcole.

I just opened https://github.com/jtpio/voila-gpx-viewer/pull/22 to update a couple of dependencies. And it seems to be working fine locally:

![image](https://user-images.githubusercontent.com/591645/105720037-415c6380-5f23-11eb-8625-5d6ee824a8e3.png)

Or on Binder:

https://mybinder.org/v2/gh/jtpio/voila-gpx-viewer/master?urlpath=voila%2Frender%2Fapp.ipynb

**Comment by jtpio** [comment]
Could it be because Voila was installed in an existing environment with potentially conflicting dependencies?

**Comment by robmarkcole** [comment]
I pulled latest on master and refreshed my conda env, now no errors. Thanks!
